### ISSUE TITLE
adsbclient.py: bad month number 0; must be 1-12 with python-dateutil-2.8.1 (works with 2.5.3)

### ISSUE THREAD

**Issue by elmicha** [kanflo/ADS-B-funhouse#4]
Thank you for your great program!

It worked happily on one of my Raspberry Pis, but when I tried to install it on another one, it crashed after a few seconds:

```
pi@rpi2:~/src/ADS-B-funhouse $ ./adsbclient.py --dump1090-host rpi2 --radar-name rpi2 --mqtt-host rpi --mqtt-user adsbclient --mqtt-password adsbclient
Connected with result code 0
2019-11-08 17:17:09,541 - __main__ - INFO - ADSB connected
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/usr/lib/python3.5/calendar.py", line 121, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 0; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./adsbclient.py", line 251, in adsbThread
    m = sbs1.SBS1Message(data)
  File "/home/pi/src/ADS-B-funhouse/sbs1.py", line 77, in __init__
    self.loggedDate = self.parseDateTime(parts, 8, 9)
  File "/home/pi/src/ADS-B-funhouse/sbs1.py", line 200, in parseDateTime
    d = dateutil.parser.parse("%s %s" % (date, time))
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

2019-11-08 17:17:10,042 - __main__ - CRITICAL - Exiting
```
I had used `sudo pip3 install python-dateutil` (and also `requests`), because it was not yet installed. I found that the other Pi had python-dateutil-2.5.3, so I did

    sudo pip3 uninstall python-dateutil
    sudo pip3 install python-dateutil==2.5.3

and now it works.

I also tried it with 2.7.5 and this one says:
```
/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1204: UnknownTimezoneWarning: tzname ED identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)
```

I'm not a Python programmer, so I don't know what that means.

**Comment by kanflo** [comment]
Thanks, glad it's of use :) I do not think I have tried the tools on Python 3 but it really seem like they changed the index of January in dateutil. I will have a look at it.

**Comment by kanflo** [comment]
Not sure when I fixed it but nowadays it works with python-dateutil 2.8.1.
